TASK 1 - 1.Write a function to compute 5/0 and use try/except to catch the exceptions

In [1]:
try:
    answer = 5 / 0
except Exception as e:
    print(e)

division by zero


TASK 1 - 2.Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [5]:
def gen_sentences(l1, l2, l3):
    for i in l1:
        for j in l2:
            for k in l3:
                yield "{} {} {}".format(i, j, k)

Subjects = ["Americans", "Indians"]
Verbs = ["play", "watch"]
Objects = ["baseball", "cricket"]
for line in gen_sentences(Subjects, Verbs, Objects):
    print(line)


Americans play baseball
Americans play cricket
Americans watch baseball
Americans watch cricket
Indians play baseball
Indians play cricket
Indians watch baseball
Indians watch cricket


TASK 2 - 1. Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False,the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [13]:
import numpy as np

def generate_matrix(input_vector, n, increasing_arg):
    """ This function will generate the output matrix"""

    if increasing_arg == 'False':
    
        output_matrix = np.array([x ** (n-i-1) for x in input_vector for i in range(n)]).reshape(len(input_vector), n)
    else:
        
        output_matrix = np.array([x ** i for x in input_vector for i in range(n)]).reshape(len(input_vector), n)
    
    return output_matrix

ip_vector = list(map(int, input("Enter the input vector (separated by spaces)").split(" ")))

N = int(input("Enter the value of n "))

increasing = input("Enter the value of increaisng argument - True/False ")

print(generate_matrix(ip_vector, N, increasing))


Enter the input vector (separated by spaces)2 4 5 6 7
Enter the value of n 3
Enter the value of increaisng argument - True/False True
[[ 1  2  4]
 [ 1  4 16]
 [ 1  5 25]
 [ 1  6 36]
 [ 1  7 49]]
